In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
data=pd.read_csv(r"C:\Users\Lenovo\Desktop\Python\Datasets/winequalityN.csv")
data

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6492    red            6.2             0.600         0.08             2.0   
6493    red            5.9             0.550         0.10             2.2   
6494    red            6.3             0.510         0.13             2.3   
6495    red            5.9             0.645         0.12             2.0   
6496    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6492      0.090                 32.0                  44.0  0.99490  3.45   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
4          0.40      9.9        6  
...         ...      ...      ...  
6492       0.58     10.5        5  
6493        NaN     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6  

[6497 rows x 13 columns]

In [4]:
data["quality"].unique()                # it shows it is multiclass data

array([6, 5, 7, 8, 4, 3, 9], dtype=int64)

In [5]:
data["type"].unique()

array(['white', 'red'], dtype=object)

In [6]:
data.shape

(6497, 13)

In [7]:
data.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [8]:
data.isnull().sum()

type                     0
fixed acidity           10
volatile acidity         8
citric acid              3
residual sugar           2
chlorides                2
free sulfur dioxide      0
total sulfur dioxide     0
density                  0
pH                       9
sulphates                4
alcohol                  0
quality                  0
dtype: int64

In [9]:
data["fixed acidity"]=data["fixed acidity"].ffill()
data["volatile acidity"]=data["volatile acidity"].ffill()
data["pH"]=data["pH"].ffill()
data["sulphates"]=data["sulphates"].ffill()

In [10]:
data.isnull().sum()

type                    0
fixed acidity           0
volatile acidity        0
citric acid             3
residual sugar          2
chlorides               2
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [11]:
data1=data.dropna()

In [12]:
data1.isnull().sum()

type                    0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [13]:
data1["quality"].value_counts()

6    2832
5    2137
7    1078
4     215
8     193
3      30
9       5
Name: quality, dtype: int64

In [14]:
data1["type"].value_counts()

white    4892
red      1598
Name: type, dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
data1["type"]=l.fit_transform(data1["type"])

C:\Users\Lenovo\AppData\Local\Temp/ipykernel_5268/852335090.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1["type"]=l.fit_transform(data1["type"])


In [16]:
data1["type"].value_counts()

1    4892
0    1598
Name: type, dtype: int64

In [17]:
from imblearn.over_sampling import RandomOverSampler

In [18]:
x=data1.iloc[:,:-1].values
y=data1.iloc[:,-1].values

In [19]:
r=RandomOverSampler()
x_data,y_data=r.fit_resample(x,y)

In [20]:
data1["type"].value_counts()

1    4892
0    1598
Name: type, dtype: int64

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=40)

In [22]:
from sklearn.naive_bayes import GaussianNB

In [23]:
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB()

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
y_pred=nb.predict(x_test)
print(y_pred)

ac=accuracy_score(y_pred,y_test)*100
print("NB Accuracy: ",ac)

[9 9 9 ... 9 8 4]
NB Accuracy:  37.957124842370746


In [26]:
from sklearn.preprocessing import MinMaxScaler
mn=MinMaxScaler()
x_train_scale=mn.fit_transform(x_train)
x_test_scale=mn.fit_transform(x_test)

In [27]:
print(np.min(x_train_scale),"------",np.max(x_train_scale))

0.0 ------ 1.0000000000000002


In [28]:
y_pred1=nb.predict(x_test_scale)
y_pred1

array([6, 6, 6, ..., 6, 6, 6], dtype=int64)

In [29]:
ac1=accuracy_score(y_pred1,y_test)*100
ac1

14.07313997477932

In [30]:
data.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [31]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()

In [32]:
data["type"]=l.fit_transform(data["type"])

In [33]:
from sklearn.preprocessing import MaxAbsScaler

In [34]:
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [35]:
ma=MaxAbsScaler()

In [36]:
x_train_scale1=ma.fit_transform(x_train)
x_test_scale1=ma.fit_transform(x_test)

In [37]:
print(np.min(x_train_scale1),"------",np.max(x_train_scale1))

0.0 ------ 1.0


In [39]:
y_pred2=nb.predict(x_test_scale1)
print(y_pred2)

[3 3 3 ... 3 3 3]


In [40]:
ac3=accuracy_score(y_pred2,y_test)*100
ac3

14.224464060529634

In [42]:
from sklearn.preprocessing import RobustScaler

In [43]:
rs=RobustScaler()
x_train_scale2=rs.fit_transform(x_train)
x_test_scale2=rs.fit_transform(x_test)

In [44]:
y_pred3=nb.predict(x_test_scale2)
print(y_pred3)

[6 6 6 ... 6 6 6]


In [45]:
ac4=accuracy_score(y_test,y_pred3)*100
ac4

18.814627994955863

In [46]:
print(np.min(x_train_scale2),"___",np.max(x_test_scale2))

-2.8181818181818192 ___ 21.846153846153847
